### ISSUE TITLE
Load the full dataset to kaggle

### ISSUE THREAD

**Issue by jkimmeyer** [FanchenBao/detect_empty_parking_spot#1]
Hey, thx for sharing your results! 

Can you maybe upload your full dataset to kaggle? There are currently just 2MB available and not 2Gigs :D

**Comment by FanchenBao** [comment]
I should've made it clearer in the readme that the training data is just 2 MB. The GB of data I was referring to was the frames generated after prediction. These frames (1000 of them, each about 3.3 MB in size) are not used for model training, but for creating the final video. Therefore, I don't think it is necessary to include them in the dataset.

That said, I do have a few frames extracted from the original video that is useful for playing around the notebook without the need to get the video itself. I will include them in the dataset on Kaggle.

**Comment by FanchenBao** [comment]
[The data set on Kaggle](https://www.kaggle.com/fanchenbao/parking-spots) has been updated with additional sample frames.
